# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app/back

# Copy package.json and package-lock.json to the working directory
COPY back/package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY back/ .

# Make port 8081 available to the world outside this container
EXPOSE 8081

# Define the command to run the app
CMD [ "node", "server.js" ]
