export const GAMES = [
  { title: "Elden Ring", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/library_600x900.jpg" },
  { title: "God of War", genre: "Acción", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1593500/library_600x900.jpg" },
  { title: "Hollow Knight", genre: "Metroidvania", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/library_600x900.jpg" },
  { title: "Cyberpunk 2077", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/library_600x900.jpg" },
  { title: "The Witcher 3", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/292030/library_600x900.jpg" },
  { title: "Hades", genre: "Roguelike", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/library_600x900.jpg" },
  { title: "Celeste", genre: "Plataformas", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/504230/library_600x900.jpg" },
  { title: "Dark Souls III", genre: "Soulslike", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/374320/library_600x900.jpg" },
  { title: "Disco Elysium", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/632470/library_600x900.jpg" },
  { title: "Sekiro", genre: "Acción", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/814380/library_600x900.jpg" },
  { title: "Baldur's Gate 3", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1086940/library_600x900.jpg" },
  { title: "Red Dead 2", genre: "Aventura", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1174180/library_600x900.jpg" },
  { title: "Persona 5", genre: "JRPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1687950/library_600x900.jpg" },
  { title: "Stardew Valley", genre: "Simulación", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/library_600x900.jpg" },
  { title: "Ori Forest", genre: "Plataformas", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1057090/library_600x900.jpg" },
  { title: "NieR: Automata", genre: "Acción RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/524220/library_600x900.jpg" },
  { title: "Spiritfarer", genre: "Gestión", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/972660/library_600x900.jpg" },
  { title: "Monster Hunter", genre: "Acción", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/582010/library_600x900.jpg" },
  { title: "Undertale", genre: "RPG", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/391540/library_600x900.jpg" },
  { title: "Outer Wilds", genre: "Exploración", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753640/library_600x900.jpg" },
  { title: "Hades II", genre: "Roguelike", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145350/library_600x900.jpg" },
  { title: "Satisfactory", genre: "Construcción", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/526870/library_600x900.jpg" },
  { title: "Tunic", genre: "Aventura", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/553420/library_600x900.jpg" },
  { title: "Cocoon", genre: "Puzzle", imageUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1497440/library_600x900.jpg" },
];
